/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Factory.AOEFM;
import Factory.Creadores.personajes;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import java.time.format.SignStyle;
import java.util.ArrayList;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author aguil
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcion = new javax.swing.JComboBox<>();
        numero = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        infoCasco = new javax.swing.JLabel();
        infoArmadura = new javax.swing.JLabel();
        infoArma = new javax.swing.JLabel();
        infoAnimal = new javax.swing.JLabel();
        imgArmadura = new javax.swing.JLabel();
        imgAnimal = new javax.swing.JLabel();
        imgCasco1 = new javax.swing.JLabel();
        imgArma1 = new javax.swing.JLabel();
        imgPersonaje = new javax.swing.JLabel();
        propPersonaje = new javax.swing.JTextArea();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Orco", "Elfo", " " }));
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 181, 46));
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 134, 46));
        numero.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {
                    e.consume();
                }
            }
        });

        boton.setText("Crear");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 116, 46));
        getContentPane().add(infoCasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 84, 30));
        getContentPane().add(infoArmadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 84, 30));
        getContentPane().add(infoArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 78, 30));
        getContentPane().add(infoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 534, 84, 20));
        getContentPane().add(imgArmadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 93, 111, 120));
        getContentPane().add(imgAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 487, 111, 101));
        getContentPane().add(imgCasco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 239, 111, 101));
        getContentPane().add(imgArma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 368, 111, 101));
        getContentPane().add(imgPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 270, 520));

        propPersonaje.setEditable(false);
        propPersonaje.setColumns(20);
        propPersonaje.setRows(5);
        getContentPane().add(propPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 100, 310));
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 80, 90));
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 80, 90));
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 80, 90));
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, 80, 90));
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 80, 90));
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 80, 90));
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 80, 90));
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 260, 80, 90));
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, 80, 90));
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 80, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
       label1.setIcon(null);
       label2.setIcon(null);
       label3.setIcon(null);
       label4.setIcon(null);
       label5.setIcon(null);
       label6.setIcon(null);
       label7.setIcon(null);
       label8.setIcon(null);
       label9.setIcon(null);
       label10.setIcon(null);
        if (Integer.parseInt(numero.getText())<1 || Integer.parseInt(numero.getText())>10){
            JOptionPane.showMessageDialog(null, "Solo se puede un mínimo de 1 o un máximo de 10");
        }
        else{a.operacion(opcion.getSelectedIndex(), Integer.parseInt(numero.getText()));
        escribir();
        }
        
        
    }//GEN-LAST:event_botonActionPerformed
    
    public void escribir(){
        
       ArrayList<String> aux= a.salida();
       this.infoCasco.setText("Protección: "+ aux.get(5));
       this.infoArmadura.setText("Protección: "+ aux.get(4));
       this.infoArma.setText("Daño: "+ aux.get(6));
       this.infoAnimal.setText("Velocidad: " + aux.get(12));
       this.propPersonaje.setText("vida= "+aux.get(0)+"\n"+"mana= "+aux.get(1)+"\n"+"Fuerza= "+aux.get(2)+"\n"+"velocidad= "+aux.get(3)+"\n"+"Puntos de \n Armadura= "+(aux.get(5)+aux.get(4)));
       
       
       this.imgPersonaje.setIcon(crearImagen(this.imgPersonaje, aux.get(7)));
       this.imgCasco1.setIcon(crearImagen(this.imgCasco1, aux.get(8)));
       this.imgArmadura.setIcon(crearImagen(this.imgArmadura, aux.get(10)));
       this.imgArma1.setIcon(crearImagen(this.imgArma1, aux.get(9)));
       this.imgAnimal.setIcon(crearImagen(this.imgAnimal,aux.get(11)));
       for (int i=1; i<=Integer.parseInt(numero.getText());i++){
           personajess(aux.get(7),i);
       }
    }

    private ImageIcon crearImagen(JLabel label, String url){
        return new ImageIcon(new ImageIcon(url).getImage().getScaledInstance(label.getWidth(), label.getHeight(),java.awt.Image.SCALE_SMOOTH));
    }
    
    
    
    public void personajess(String img, int i){
        switch (i){
        case 1:
        this.label1.setIcon(crearImagen(this.label1,img));
        break;
        case 2:
        this.label2.setIcon(crearImagen(this.label2,img));
        break;
        case 3:
        this.label3.setIcon(crearImagen(this.label3,img));
        break;
        case 4:
        this.label4.setIcon(crearImagen(this.label4,img));
        break;
        case 5:
        this.label5.setIcon(crearImagen(this.label5,img));
        break;
        case 6:
        this.label6.setIcon(crearImagen(this.label6,img));
        break;
        case 7:
        this.label7.setIcon(crearImagen(this.label7,img));
        break;
        case 8:
        this.label8.setIcon(crearImagen(this.label8,img));
        break;
        case 9:
        this.label9.setIcon(crearImagen(this.label9,img));
        break;
        case 10:
        this.label10.setIcon(crearImagen(this.label10,img));
        break;
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public void correr() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
   
    AOEFM a = new AOEFM();  
      
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JLabel imgAnimal;
    private javax.swing.JLabel imgArma1;
    private javax.swing.JLabel imgArmadura;
    private javax.swing.JLabel imgCasco1;
    private javax.swing.JLabel imgPersonaje;
    private javax.swing.JLabel infoAnimal;
    private javax.swing.JLabel infoArma;
    private javax.swing.JLabel infoArmadura;
    private javax.swing.JLabel infoCasco;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JTextField numero;
    private javax.swing.JComboBox<String> opcion;
    private javax.swing.JTextArea propPersonaje;
    // End of variables declaration//GEN-END:variables
}
